import { classifiedAsset } from "@/lib/prototype-assets";

export const prototypeAssetManifest = [
  { key: "decor/doodle/doodle_heart_01", path: classifiedAsset("decor/doodle/doodle_heart_01.png") },
  { key: "decor/doodle/doodle_heart_02", path: classifiedAsset("decor/doodle/doodle_heart_02.png") },
  { key: "decor/doodle/doodle_heart_glow", path: classifiedAsset("decor/doodle/doodle_heart_glow.png") },
  { key: "decor/doodle/doodle_leaf_01", path: classifiedAsset("decor/doodle/doodle_leaf_01.png") },
  { key: "decor/doodle/doodle_leaf_02", path: classifiedAsset("decor/doodle/doodle_leaf_02.png") },
  { key: "decor/paper_strip/paper_strip_beige_long", path: classifiedAsset("decor/paper_strip/paper_strip_beige_long.png") },
  { key: "decor/paper_strip/paper_strip_kraft_long", path: classifiedAsset("decor/paper_strip/paper_strip_kraft_long.png") },
  { key: "decor/paper_strip/paper_strip_orange_long", path: classifiedAsset("decor/paper_strip/paper_strip_orange_long.png") },
  { key: "decor/paper_strip/paper_strip_sage_long", path: classifiedAsset("decor/paper_strip/paper_strip_sage_long.png") },
  { key: "decor/paperclip/paperclip_angle", path: classifiedAsset("decor/paperclip/paperclip_angle.png") },
  { key: "decor/paperclip/paperclip_medium", path: classifiedAsset("decor/paperclip/paperclip_medium.png") },
  { key: "decor/paperclip/paperclip_small", path: classifiedAsset("decor/paperclip/paperclip_small.png") },
  { key: "decor/polaroid/polaroid_frame_empty", path: classifiedAsset("decor/polaroid/polaroid_frame_empty.png") },
  { key: "decor/polaroid/polaroid_frame_taped", path: classifiedAsset("decor/polaroid/polaroid_frame_taped.png") },
  { key: "decor/postmark/postmark_secret", path: classifiedAsset("decor/postmark/postmark_secret.png") },
  { key: "decor/postmark/postmark_sent", path: classifiedAsset("decor/postmark/postmark_sent.png") },
  { key: "decor/stamp/stamp_flower", path: classifiedAsset("decor/stamp/stamp_flower.png") },
  { key: "decor/stamp/stamp_heart", path: classifiedAsset("decor/stamp/stamp_heart.png") },
  { key: "decor/stamp/stamp_leaf", path: classifiedAsset("decor/stamp/stamp_leaf.png") },
  { key: "decor/tape/tape_01", path: classifiedAsset("decor/tape/tape_01.png") },
  { key: "decor/tape/tape_02", path: classifiedAsset("decor/tape/tape_02.png") },
  { key: "decor/tape/tape_03", path: classifiedAsset("decor/tape/tape_03.png") },
  { key: "decor/tape/tape_04", path: classifiedAsset("decor/tape/tape_04.png") },
  { key: "decor/wax_seal/wax_seal_blank", path: classifiedAsset("decor/wax_seal/wax_seal_blank.png") },
  { key: "decor/wax_seal/wax_seal_cream_blank", path: classifiedAsset("decor/wax_seal/wax_seal_cream_blank.png") },
  { key: "decor/wax_seal/wax_seal_kraft_blank", path: classifiedAsset("decor/wax_seal/wax_seal_kraft_blank.png") },
  { key: "decor/wax_seal/wax_seal_leaf", path: classifiedAsset("decor/wax_seal/wax_seal_leaf.png") },
  { key: "decor/wax_seal/wax_seal_orange_blank", path: classifiedAsset("decor/wax_seal/wax_seal_orange_blank.png") },
  { key: "decor/wax_seal/wax_seal_red", path: classifiedAsset("decor/wax_seal/wax_seal_red.png") },
  { key: "decor/wax_seal/wax_seal_sage_blank", path: classifiedAsset("decor/wax_seal/wax_seal_sage_blank.png") },
  { key: "objects/album/album_closed", path: classifiedAsset("objects/album/album_closed.png") },
  { key: "objects/album/album_grid", path: classifiedAsset("objects/album/album_grid.png") },
  { key: "objects/album/album_open", path: classifiedAsset("objects/album/album_open.png") },
  { key: "objects/album/album_photo_view", path: classifiedAsset("objects/album/album_photo_view.png") },
  { key: "objects/book/book_closed", path: classifiedAsset("objects/book/book_closed.png") },
  { key: "objects/book/book_open", path: classifiedAsset("objects/book/book_open.png") },
  { key: "objects/book/book_viewed", path: classifiedAsset("objects/book/book_viewed.png") },
  { key: "objects/chat_note/chat_note_active", path: classifiedAsset("objects/chat_note/chat_note_active.png") },
  { key: "objects/chat_note/chat_note_dark", path: classifiedAsset("objects/chat_note/chat_note_dark.png") },
  { key: "objects/chat_note/chat_note_viewed", path: classifiedAsset("objects/chat_note/chat_note_viewed.png") },
  { key: "objects/clock/clock_active", path: classifiedAsset("objects/clock/clock_active.png") },
  { key: "objects/clock/clock_default", path: classifiedAsset("objects/clock/clock_default.png") },
  { key: "objects/clock/clock_viewed", path: classifiedAsset("objects/clock/clock_viewed.png") },
  { key: "objects/cup/cup_default", path: classifiedAsset("objects/cup/cup_default.png") },
  { key: "objects/cup/cup_viewed", path: classifiedAsset("objects/cup/cup_viewed.png") },
  { key: "objects/cup/cup_warm", path: classifiedAsset("objects/cup/cup_warm.png") },
  { key: "objects/diary/diary_80_percent_card", path: classifiedAsset("objects/diary/diary_80_percent_card.png") },
  { key: "objects/diary/diary_80_percent_note", path: classifiedAsset("objects/diary/diary_80_percent_note.png") },
  { key: "objects/diary/diary_condition_near_unlock", path: classifiedAsset("objects/diary/diary_condition_near_unlock.png") },
  { key: "objects/diary/diary_condition_unmet", path: classifiedAsset("objects/diary/diary_condition_unmet.png") },
  { key: "objects/diary/diary_lock_unmet_card", path: classifiedAsset("objects/diary/diary_lock_unmet_card.png") },
  { key: "objects/diary/diary_locked", path: classifiedAsset("objects/diary/diary_locked.png") },
  { key: "objects/diary/diary_near_unlock_card", path: classifiedAsset("objects/diary/diary_near_unlock_card.png") },
  { key: "objects/diary/diary_open", path: classifiedAsset("objects/diary/diary_open.png") },
  { key: "objects/diary/diary_requestable", path: classifiedAsset("objects/diary/diary_requestable.png") },
  { key: "objects/diary/diary_unlocked", path: classifiedAsset("objects/diary/diary_unlocked.png") },
  { key: "objects/diary/diary_unlocked_card", path: classifiedAsset("objects/diary/diary_unlocked_card.png") },
  { key: "objects/diary/diary_unlocked_note", path: classifiedAsset("objects/diary/diary_unlocked_note.png") },
  { key: "objects/envelope/envelope_closed", path: classifiedAsset("objects/envelope/envelope_closed.png") },
  { key: "objects/envelope/envelope_open", path: classifiedAsset("objects/envelope/envelope_open.png") },
  { key: "objects/envelope/envelope_sealed", path: classifiedAsset("objects/envelope/envelope_sealed.png") },
  { key: "objects/envelope/envelope_with_letter", path: classifiedAsset("objects/envelope/envelope_with_letter.png") },
  { key: "objects/envelope/envelope_with_photo", path: classifiedAsset("objects/envelope/envelope_with_photo.png") },
  { key: "objects/guess/guess_card_empty", path: classifiedAsset("objects/guess/guess_card_empty.png") },
  { key: "objects/guess/guess_card_selected", path: classifiedAsset("objects/guess/guess_card_selected.png") },
  { key: "objects/guess/guess_card_submitted", path: classifiedAsset("objects/guess/guess_card_submitted.png") },
  { key: "objects/guess/guess_card_success", path: classifiedAsset("objects/guess/guess_card_success.png") },
  { key: "objects/guess/guess_card_waiting", path: classifiedAsset("objects/guess/guess_card_waiting.png") },
  { key: "objects/guess/guess_result_forgot", path: classifiedAsset("objects/guess/guess_result_forgot.png") },
  { key: "objects/guess/guess_result_love", path: classifiedAsset("objects/guess/guess_result_love.png") },
  { key: "objects/guess/guess_result_pressure", path: classifiedAsset("objects/guess/guess_result_pressure.png") },
  { key: "objects/guess/guess_submitted_small", path: classifiedAsset("objects/guess/guess_submitted_small.png") },
  { key: "objects/guess/guess_waiting_small", path: classifiedAsset("objects/guess/guess_waiting_small.png") },
  { key: "objects/key/key_active", path: classifiedAsset("objects/key/key_active.png") },
  { key: "objects/key/key_default", path: classifiedAsset("objects/key/key_default.png") },
  { key: "objects/key/key_viewed", path: classifiedAsset("objects/key/key_viewed.png") },
  { key: "objects/plant/plant_default", path: classifiedAsset("objects/plant/plant_default.png") },
  { key: "objects/plant/plant_viewed", path: classifiedAsset("objects/plant/plant_viewed.png") },
  { key: "objects/star/star_active", path: classifiedAsset("objects/star/star_active.png") },
  { key: "objects/star/star_default", path: classifiedAsset("objects/star/star_default.png") },
  { key: "objects/star/star_viewed", path: classifiedAsset("objects/star/star_viewed.png") },
  { key: "objects/upload_envelope/upload_envelope_empty", path: classifiedAsset("objects/upload_envelope/upload_envelope_empty.png") },
  { key: "objects/upload_envelope/upload_envelope_plus", path: classifiedAsset("objects/upload_envelope/upload_envelope_plus.png") },
  { key: "objects/upload_envelope/upload_envelope_uploaded", path: classifiedAsset("objects/upload_envelope/upload_envelope_uploaded.png") },
  { key: "ui/buttons/button_hide_secret", path: classifiedAsset("ui/buttons/button_hide_secret.png") },
  { key: "ui/buttons/button_selected", path: classifiedAsset("ui/buttons/button_selected.png") },
  { key: "ui/buttons/button_view_others", path: classifiedAsset("ui/buttons/button_view_others.png") },
  { key: "ui/buttons/paper_button_guessed", path: classifiedAsset("ui/buttons/paper_button_guessed.png") },
  { key: "ui/buttons/paper_button_pressed", path: classifiedAsset("ui/buttons/paper_button_pressed.png") },
  { key: "ui/buttons/paper_button_primary", path: classifiedAsset("ui/buttons/paper_button_primary.png") },
  { key: "ui/buttons/paper_button_save_again", path: classifiedAsset("ui/buttons/paper_button_save_again.png") },
  { key: "ui/buttons/paper_button_secondary", path: classifiedAsset("ui/buttons/paper_button_secondary.png") },
  { key: "ui/buttons/paper_button_send_guess", path: classifiedAsset("ui/buttons/paper_button_send_guess.png") },
  { key: "ui/clue_note/clue_note_closed", path: classifiedAsset("ui/clue_note/clue_note_closed.png") },
  { key: "ui/clue_note/clue_note_large_example", path: classifiedAsset("ui/clue_note/clue_note_large_example.png") },
  { key: "ui/clue_note/clue_note_open", path: classifiedAsset("ui/clue_note/clue_note_open.png") },
  { key: "ui/clue_note/clue_note_viewed", path: classifiedAsset("ui/clue_note/clue_note_viewed.png") },
  { key: "ui/message_note/message_note_empty", path: classifiedAsset("ui/message_note/message_note_empty.png") },
  { key: "ui/message_note/message_note_sent", path: classifiedAsset("ui/message_note/message_note_sent.png") },
  { key: "ui/message_note/message_note_written", path: classifiedAsset("ui/message_note/message_note_written.png") },
  { key: "ui/notes/note_medium", path: classifiedAsset("ui/notes/note_medium.png") },
  { key: "ui/notes/note_narrow_leaf", path: classifiedAsset("ui/notes/note_narrow_leaf.png") },
  { key: "ui/notes/note_narrow_plain", path: classifiedAsset("ui/notes/note_narrow_plain.png") },
  { key: "ui/notes/note_popup", path: classifiedAsset("ui/notes/note_popup.png") },
  { key: "ui/notes/note_quote_soft", path: classifiedAsset("ui/notes/note_quote_soft.png") },
  { key: "ui/notes/note_small", path: classifiedAsset("ui/notes/note_small.png") },
  { key: "ui/notes/note_taped_flower", path: classifiedAsset("ui/notes/note_taped_flower.png") },
  { key: "ui/notes/note_vertical_plain", path: classifiedAsset("ui/notes/note_vertical_plain.png") },
  { key: "ui/notes/note_viewed", path: classifiedAsset("ui/notes/note_viewed.png") },
  { key: "ui/notes/note_wide_leaf", path: classifiedAsset("ui/notes/note_wide_leaf.png") },
  { key: "ui/notes/note_wide_paperclip", path: classifiedAsset("ui/notes/note_wide_paperclip.png") },
  { key: "ui/progress/affinity_badge_80_plus", path: classifiedAsset("ui/progress/affinity_badge_80_plus.png") },
  { key: "ui/progress/affinity_badge_tacit_match", path: classifiedAsset("ui/progress/affinity_badge_tacit_match.png") },
  { key: "ui/progress/affinity_badge_unlocked", path: classifiedAsset("ui/progress/affinity_badge_unlocked.png") },
  { key: "ui/progress/affinity_card_05", path: classifiedAsset("ui/progress/affinity_card_05.png") },
  { key: "ui/progress/affinity_card_100", path: classifiedAsset("ui/progress/affinity_card_100.png") },
  { key: "ui/progress/affinity_card_18", path: classifiedAsset("ui/progress/affinity_card_18.png") },
  { key: "ui/progress/affinity_card_27", path: classifiedAsset("ui/progress/affinity_card_27.png") },
  { key: "ui/progress/affinity_card_35", path: classifiedAsset("ui/progress/affinity_card_35.png") },
  { key: "ui/progress/affinity_card_49", path: classifiedAsset("ui/progress/affinity_card_49.png") },
  { key: "ui/progress/affinity_card_57", path: classifiedAsset("ui/progress/affinity_card_57.png") },
  { key: "ui/progress/affinity_card_64", path: classifiedAsset("ui/progress/affinity_card_64.png") },
  { key: "ui/progress/affinity_card_71", path: classifiedAsset("ui/progress/affinity_card_71.png") },
  { key: "ui/progress/affinity_card_80", path: classifiedAsset("ui/progress/affinity_card_80.png") },
  { key: "ui/progress/affinity_card_86", path: classifiedAsset("ui/progress/affinity_card_86.png") },
  { key: "ui/progress/affinity_card_94", path: classifiedAsset("ui/progress/affinity_card_94.png") },
  { key: "ui/progress/affinity_card_high", path: classifiedAsset("ui/progress/affinity_card_high.png") },
  { key: "ui/progress/affinity_card_large_00", path: classifiedAsset("ui/progress/affinity_card_large_00.png") },
  { key: "ui/progress/affinity_card_large_100", path: classifiedAsset("ui/progress/affinity_card_large_100.png") },
  { key: "ui/progress/affinity_card_large_12", path: classifiedAsset("ui/progress/affinity_card_large_12.png") },
  { key: "ui/progress/affinity_card_large_26", path: classifiedAsset("ui/progress/affinity_card_large_26.png") },
  { key: "ui/progress/affinity_card_large_43", path: classifiedAsset("ui/progress/affinity_card_large_43.png") },
  { key: "ui/progress/affinity_card_large_58", path: classifiedAsset("ui/progress/affinity_card_large_58.png") },
  { key: "ui/progress/affinity_card_large_72", path: classifiedAsset("ui/progress/affinity_card_large_72.png") },
  { key: "ui/progress/affinity_card_large_80", path: classifiedAsset("ui/progress/affinity_card_large_80.png") },
  { key: "ui/progress/affinity_card_large_86", path: classifiedAsset("ui/progress/affinity_card_large_86.png") },
  { key: "ui/progress/affinity_card_large_93", path: classifiedAsset("ui/progress/affinity_card_large_93.png") },
  { key: "ui/progress/affinity_card_low", path: classifiedAsset("ui/progress/affinity_card_low.png") },
  { key: "ui/progress/affinity_card_pass", path: classifiedAsset("ui/progress/affinity_card_pass.png") },
  { key: "ui/progress/affinity_stamp_80_plus", path: classifiedAsset("ui/progress/affinity_stamp_80_plus.png") },
  { key: "ui/progress/affinity_tag_keep_close", path: classifiedAsset("ui/progress/affinity_tag_keep_close.png") },
  { key: "ui/progress/affinity_tag_tacit_match", path: classifiedAsset("ui/progress/affinity_tag_tacit_match.png") },
  { key: "ui/progress/affinity_tag_unlocked", path: classifiedAsset("ui/progress/affinity_tag_unlocked.png") },
  { key: "ui/tags/clip_tag_beige", path: classifiedAsset("ui/tags/clip_tag_beige.png") },
  { key: "ui/tags/clip_tag_kraft", path: classifiedAsset("ui/tags/clip_tag_kraft.png") },
  { key: "ui/tags/clip_tag_orange", path: classifiedAsset("ui/tags/clip_tag_orange.png") },
  { key: "ui/tags/clip_tag_sage", path: classifiedAsset("ui/tags/clip_tag_sage.png") },
  { key: "ui/tags/label_beige_small", path: classifiedAsset("ui/tags/label_beige_small.png") },
  { key: "ui/tags/label_kraft_small", path: classifiedAsset("ui/tags/label_kraft_small.png") },
  { key: "ui/tags/label_orange_small", path: classifiedAsset("ui/tags/label_orange_small.png") },
  { key: "ui/tags/label_sage_small", path: classifiedAsset("ui/tags/label_sage_small.png") },
  { key: "ui/tags/lock_tag_beige", path: classifiedAsset("ui/tags/lock_tag_beige.png") },
  { key: "ui/tags/lock_tag_kraft", path: classifiedAsset("ui/tags/lock_tag_kraft.png") },
  { key: "ui/tags/lock_tag_orange", path: classifiedAsset("ui/tags/lock_tag_orange.png") },
  { key: "ui/tags/lock_tag_sage", path: classifiedAsset("ui/tags/lock_tag_sage.png") },
  { key: "ui/tags/number_token_1_active", path: classifiedAsset("ui/tags/number_token_1_active.png") },
  { key: "ui/tags/number_token_1_default", path: classifiedAsset("ui/tags/number_token_1_default.png") },
  { key: "ui/tags/number_token_1_disabled", path: classifiedAsset("ui/tags/number_token_1_disabled.png") },
  { key: "ui/tags/number_token_2_active", path: classifiedAsset("ui/tags/number_token_2_active.png") },
  { key: "ui/tags/number_token_2_default", path: classifiedAsset("ui/tags/number_token_2_default.png") },
  { key: "ui/tags/number_token_2_disabled", path: classifiedAsset("ui/tags/number_token_2_disabled.png") },
  { key: "ui/tags/number_token_3_active", path: classifiedAsset("ui/tags/number_token_3_active.png") },
  { key: "ui/tags/number_token_3_default", path: classifiedAsset("ui/tags/number_token_3_default.png") },
  { key: "ui/tags/number_token_3_disabled", path: classifiedAsset("ui/tags/number_token_3_disabled.png") },
  { key: "ui/tags/number_token_4_active", path: classifiedAsset("ui/tags/number_token_4_active.png") },
  { key: "ui/tags/number_token_4_default", path: classifiedAsset("ui/tags/number_token_4_default.png") },
  { key: "ui/tags/number_token_4_disabled", path: classifiedAsset("ui/tags/number_token_4_disabled.png") },
  { key: "ui/tags/number_token_5_active", path: classifiedAsset("ui/tags/number_token_5_active.png") },
  { key: "ui/tags/number_token_5_default", path: classifiedAsset("ui/tags/number_token_5_default.png") },
  { key: "ui/tags/number_token_5_disabled", path: classifiedAsset("ui/tags/number_token_5_disabled.png") },
  { key: "ui/tags/status_blank", path: classifiedAsset("ui/tags/status_blank.png") },
  { key: "ui/tags/status_blank_small", path: classifiedAsset("ui/tags/status_blank_small.png") },
  { key: "ui/tags/status_line_example", path: classifiedAsset("ui/tags/status_line_example.png") },
  { key: "ui/tags/status_selected", path: classifiedAsset("ui/tags/status_selected.png") },
  { key: "ui/tags/status_sent", path: classifiedAsset("ui/tags/status_sent.png") },
  { key: "ui/tags/status_submitted", path: classifiedAsset("ui/tags/status_submitted.png") },
  { key: "ui/tags/status_success", path: classifiedAsset("ui/tags/status_success.png") },
  { key: "ui/tags/status_waiting", path: classifiedAsset("ui/tags/status_waiting.png") },
  { key: "ui/tags/status_written", path: classifiedAsset("ui/tags/status_written.png") },
  { key: "ui/tags/tag_blue_gray", path: classifiedAsset("ui/tags/tag_blue_gray.png") },
  { key: "ui/tags/tag_hole_beige", path: classifiedAsset("ui/tags/tag_hole_beige.png") },
  { key: "ui/tags/tag_hole_orange", path: classifiedAsset("ui/tags/tag_hole_orange.png") },
  { key: "ui/tags/tag_hole_sage", path: classifiedAsset("ui/tags/tag_hole_sage.png") },
  { key: "ui/tags/tag_orange", path: classifiedAsset("ui/tags/tag_orange.png") },
  { key: "ui/tags/tag_red", path: classifiedAsset("ui/tags/tag_red.png") },
  { key: "ui/tags/tag_sage", path: classifiedAsset("ui/tags/tag_sage.png") },
  { key: "ui/tags/tag_selected", path: classifiedAsset("ui/tags/tag_selected.png") },
  { key: "ui/tags/taped_note_blank", path: classifiedAsset("ui/tags/taped_note_blank.png") },
  { key: "ui/tags/ticket_tag_beige", path: classifiedAsset("ui/tags/ticket_tag_beige.png") },
  { key: "ui/tags/ticket_tag_kraft", path: classifiedAsset("ui/tags/ticket_tag_kraft.png") },
  { key: "ui/tags/ticket_tag_orange", path: classifiedAsset("ui/tags/ticket_tag_orange.png") },
  { key: "ui/tags/ticket_tag_sage", path: classifiedAsset("ui/tags/ticket_tag_sage.png") },
] as const;

export type PrototypeAssetKey = (typeof prototypeAssetManifest)[number]["key"];

export const prototypeAssetByKey = Object.fromEntries(
  prototypeAssetManifest.map((asset) => [asset.key, asset.path])
) as Record<PrototypeAssetKey, string>;

export const prototypeAssets = {
  decor: {
    doodle: {
      doodleHeart01: classifiedAsset("decor/doodle/doodle_heart_01.png"),
      doodleHeart02: classifiedAsset("decor/doodle/doodle_heart_02.png"),
      doodleHeartGlow: classifiedAsset("decor/doodle/doodle_heart_glow.png"),
      doodleLeaf01: classifiedAsset("decor/doodle/doodle_leaf_01.png"),
      doodleLeaf02: classifiedAsset("decor/doodle/doodle_leaf_02.png"),
    },
    paperStrip: {
      paperStripBeigeLong: classifiedAsset("decor/paper_strip/paper_strip_beige_long.png"),
      paperStripKraftLong: classifiedAsset("decor/paper_strip/paper_strip_kraft_long.png"),
      paperStripOrangeLong: classifiedAsset("decor/paper_strip/paper_strip_orange_long.png"),
      paperStripSageLong: classifiedAsset("decor/paper_strip/paper_strip_sage_long.png"),
    },
    paperclip: {
      paperclipAngle: classifiedAsset("decor/paperclip/paperclip_angle.png"),
      paperclipMedium: classifiedAsset("decor/paperclip/paperclip_medium.png"),
      paperclipSmall: classifiedAsset("decor/paperclip/paperclip_small.png"),
    },
    polaroid: {
      polaroidFrameEmpty: classifiedAsset("decor/polaroid/polaroid_frame_empty.png"),
      polaroidFrameTaped: classifiedAsset("decor/polaroid/polaroid_frame_taped.png"),
    },
    postmark: {
      postmarkSecret: classifiedAsset("decor/postmark/postmark_secret.png"),
      postmarkSent: classifiedAsset("decor/postmark/postmark_sent.png"),
    },
    stamp: {
      stampFlower: classifiedAsset("decor/stamp/stamp_flower.png"),
      stampHeart: classifiedAsset("decor/stamp/stamp_heart.png"),
      stampLeaf: classifiedAsset("decor/stamp/stamp_leaf.png"),
    },
    tape: {
      tape01: classifiedAsset("decor/tape/tape_01.png"),
      tape02: classifiedAsset("decor/tape/tape_02.png"),
      tape03: classifiedAsset("decor/tape/tape_03.png"),
      tape04: classifiedAsset("decor/tape/tape_04.png"),
    },
    waxSeal: {
      waxSealBlank: classifiedAsset("decor/wax_seal/wax_seal_blank.png"),
      waxSealCreamBlank: classifiedAsset("decor/wax_seal/wax_seal_cream_blank.png"),
      waxSealKraftBlank: classifiedAsset("decor/wax_seal/wax_seal_kraft_blank.png"),
      waxSealLeaf: classifiedAsset("decor/wax_seal/wax_seal_leaf.png"),
      waxSealOrangeBlank: classifiedAsset("decor/wax_seal/wax_seal_orange_blank.png"),
      waxSealRed: classifiedAsset("decor/wax_seal/wax_seal_red.png"),
      waxSealSageBlank: classifiedAsset("decor/wax_seal/wax_seal_sage_blank.png"),
    },
  },
  objects: {
    album: {
      albumClosed: classifiedAsset("objects/album/album_closed.png"),
      albumGrid: classifiedAsset("objects/album/album_grid.png"),
      albumOpen: classifiedAsset("objects/album/album_open.png"),
      albumPhotoView: classifiedAsset("objects/album/album_photo_view.png"),
    },
    book: {
      bookClosed: classifiedAsset("objects/book/book_closed.png"),
      bookOpen: classifiedAsset("objects/book/book_open.png"),
      bookViewed: classifiedAsset("objects/book/book_viewed.png"),
    },
    chatNote: {
      chatNoteActive: classifiedAsset("objects/chat_note/chat_note_active.png"),
      chatNoteDark: classifiedAsset("objects/chat_note/chat_note_dark.png"),
      chatNoteViewed: classifiedAsset("objects/chat_note/chat_note_viewed.png"),
    },
    clock: {
      clockActive: classifiedAsset("objects/clock/clock_active.png"),
      clockDefault: classifiedAsset("objects/clock/clock_default.png"),
      clockViewed: classifiedAsset("objects/clock/clock_viewed.png"),
    },
    cup: {
      cupDefault: classifiedAsset("objects/cup/cup_default.png"),
      cupViewed: classifiedAsset("objects/cup/cup_viewed.png"),
      cupWarm: classifiedAsset("objects/cup/cup_warm.png"),
    },
    diary: {
      diary80PercentCard: classifiedAsset("objects/diary/diary_80_percent_card.png"),
      diary80PercentNote: classifiedAsset("objects/diary/diary_80_percent_note.png"),
      diaryConditionNearUnlock: classifiedAsset("objects/diary/diary_condition_near_unlock.png"),
      diaryConditionUnmet: classifiedAsset("objects/diary/diary_condition_unmet.png"),
      diaryLockUnmetCard: classifiedAsset("objects/diary/diary_lock_unmet_card.png"),
      diaryLocked: classifiedAsset("objects/diary/diary_locked.png"),
      diaryNearUnlockCard: classifiedAsset("objects/diary/diary_near_unlock_card.png"),
      diaryOpen: classifiedAsset("objects/diary/diary_open.png"),
      diaryRequestable: classifiedAsset("objects/diary/diary_requestable.png"),
      diaryUnlocked: classifiedAsset("objects/diary/diary_unlocked.png"),
      diaryUnlockedCard: classifiedAsset("objects/diary/diary_unlocked_card.png"),
      diaryUnlockedNote: classifiedAsset("objects/diary/diary_unlocked_note.png"),
    },
    envelope: {
      envelopeClosed: classifiedAsset("objects/envelope/envelope_closed.png"),
      envelopeOpen: classifiedAsset("objects/envelope/envelope_open.png"),
      envelopeSealed: classifiedAsset("objects/envelope/envelope_sealed.png"),
      envelopeWithLetter: classifiedAsset("objects/envelope/envelope_with_letter.png"),
      envelopeWithPhoto: classifiedAsset("objects/envelope/envelope_with_photo.png"),
    },
    guess: {
      guessCardEmpty: classifiedAsset("objects/guess/guess_card_empty.png"),
      guessCardSelected: classifiedAsset("objects/guess/guess_card_selected.png"),
      guessCardSubmitted: classifiedAsset("objects/guess/guess_card_submitted.png"),
      guessCardSuccess: classifiedAsset("objects/guess/guess_card_success.png"),
      guessCardWaiting: classifiedAsset("objects/guess/guess_card_waiting.png"),
      guessResultForgot: classifiedAsset("objects/guess/guess_result_forgot.png"),
      guessResultLove: classifiedAsset("objects/guess/guess_result_love.png"),
      guessResultPressure: classifiedAsset("objects/guess/guess_result_pressure.png"),
      guessSubmittedSmall: classifiedAsset("objects/guess/guess_submitted_small.png"),
      guessWaitingSmall: classifiedAsset("objects/guess/guess_waiting_small.png"),
    },
    key: {
      keyActive: classifiedAsset("objects/key/key_active.png"),
      keyDefault: classifiedAsset("objects/key/key_default.png"),
      keyViewed: classifiedAsset("objects/key/key_viewed.png"),
    },
    plant: {
      plantDefault: classifiedAsset("objects/plant/plant_default.png"),
      plantViewed: classifiedAsset("objects/plant/plant_viewed.png"),
    },
    star: {
      starActive: classifiedAsset("objects/star/star_active.png"),
      starDefault: classifiedAsset("objects/star/star_default.png"),
      starViewed: classifiedAsset("objects/star/star_viewed.png"),
    },
    uploadEnvelope: {
      uploadEnvelopeEmpty: classifiedAsset("objects/upload_envelope/upload_envelope_empty.png"),
      uploadEnvelopePlus: classifiedAsset("objects/upload_envelope/upload_envelope_plus.png"),
      uploadEnvelopeUploaded: classifiedAsset("objects/upload_envelope/upload_envelope_uploaded.png"),
    },
  },
  ui: {
    buttons: {
      buttonHideSecret: classifiedAsset("ui/buttons/button_hide_secret.png"),
      buttonSelected: classifiedAsset("ui/buttons/button_selected.png"),
      buttonViewOthers: classifiedAsset("ui/buttons/button_view_others.png"),
      paperButtonGuessed: classifiedAsset("ui/buttons/paper_button_guessed.png"),
      paperButtonPressed: classifiedAsset("ui/buttons/paper_button_pressed.png"),
      paperButtonPrimary: classifiedAsset("ui/buttons/paper_button_primary.png"),
      paperButtonSaveAgain: classifiedAsset("ui/buttons/paper_button_save_again.png"),
      paperButtonSecondary: classifiedAsset("ui/buttons/paper_button_secondary.png"),
      paperButtonSendGuess: classifiedAsset("ui/buttons/paper_button_send_guess.png"),
    },
    clueNote: {
      clueNoteClosed: classifiedAsset("ui/clue_note/clue_note_closed.png"),
      clueNoteLargeExample: classifiedAsset("ui/clue_note/clue_note_large_example.png"),
      clueNoteOpen: classifiedAsset("ui/clue_note/clue_note_open.png"),
      clueNoteViewed: classifiedAsset("ui/clue_note/clue_note_viewed.png"),
    },
    messageNote: {
      messageNoteEmpty: classifiedAsset("ui/message_note/message_note_empty.png"),
      messageNoteSent: classifiedAsset("ui/message_note/message_note_sent.png"),
      messageNoteWritten: classifiedAsset("ui/message_note/message_note_written.png"),
    },
    notes: {
      noteMedium: classifiedAsset("ui/notes/note_medium.png"),
      noteNarrowLeaf: classifiedAsset("ui/notes/note_narrow_leaf.png"),
      noteNarrowPlain: classifiedAsset("ui/notes/note_narrow_plain.png"),
      notePopup: classifiedAsset("ui/notes/note_popup.png"),
      noteQuoteSoft: classifiedAsset("ui/notes/note_quote_soft.png"),
      noteSmall: classifiedAsset("ui/notes/note_small.png"),
      noteTapedFlower: classifiedAsset("ui/notes/note_taped_flower.png"),
      noteVerticalPlain: classifiedAsset("ui/notes/note_vertical_plain.png"),
      noteViewed: classifiedAsset("ui/notes/note_viewed.png"),
      noteWideLeaf: classifiedAsset("ui/notes/note_wide_leaf.png"),
      noteWidePaperclip: classifiedAsset("ui/notes/note_wide_paperclip.png"),
    },
    progress: {
      affinityBadge80Plus: classifiedAsset("ui/progress/affinity_badge_80_plus.png"),
      affinityBadgeTacitMatch: classifiedAsset("ui/progress/affinity_badge_tacit_match.png"),
      affinityBadgeUnlocked: classifiedAsset("ui/progress/affinity_badge_unlocked.png"),
      affinityCard05: classifiedAsset("ui/progress/affinity_card_05.png"),
      affinityCard100: classifiedAsset("ui/progress/affinity_card_100.png"),
      affinityCard18: classifiedAsset("ui/progress/affinity_card_18.png"),
      affinityCard27: classifiedAsset("ui/progress/affinity_card_27.png"),
      affinityCard35: classifiedAsset("ui/progress/affinity_card_35.png"),
      affinityCard49: classifiedAsset("ui/progress/affinity_card_49.png"),
      affinityCard57: classifiedAsset("ui/progress/affinity_card_57.png"),
      affinityCard64: classifiedAsset("ui/progress/affinity_card_64.png"),
      affinityCard71: classifiedAsset("ui/progress/affinity_card_71.png"),
      affinityCard80: classifiedAsset("ui/progress/affinity_card_80.png"),
      affinityCard86: classifiedAsset("ui/progress/affinity_card_86.png"),
      affinityCard94: classifiedAsset("ui/progress/affinity_card_94.png"),
      affinityCardHigh: classifiedAsset("ui/progress/affinity_card_high.png"),
      affinityCardLarge00: classifiedAsset("ui/progress/affinity_card_large_00.png"),
      affinityCardLarge100: classifiedAsset("ui/progress/affinity_card_large_100.png"),
      affinityCardLarge12: classifiedAsset("ui/progress/affinity_card_large_12.png"),
      affinityCardLarge26: classifiedAsset("ui/progress/affinity_card_large_26.png"),
      affinityCardLarge43: classifiedAsset("ui/progress/affinity_card_large_43.png"),
      affinityCardLarge58: classifiedAsset("ui/progress/affinity_card_large_58.png"),
      affinityCardLarge72: classifiedAsset("ui/progress/affinity_card_large_72.png"),
      affinityCardLarge80: classifiedAsset("ui/progress/affinity_card_large_80.png"),
      affinityCardLarge86: classifiedAsset("ui/progress/affinity_card_large_86.png"),
      affinityCardLarge93: classifiedAsset("ui/progress/affinity_card_large_93.png"),
      affinityCardLow: classifiedAsset("ui/progress/affinity_card_low.png"),
      affinityCardPass: classifiedAsset("ui/progress/affinity_card_pass.png"),
      affinityStamp80Plus: classifiedAsset("ui/progress/affinity_stamp_80_plus.png"),
      affinityTagKeepClose: classifiedAsset("ui/progress/affinity_tag_keep_close.png"),
      affinityTagTacitMatch: classifiedAsset("ui/progress/affinity_tag_tacit_match.png"),
      affinityTagUnlocked: classifiedAsset("ui/progress/affinity_tag_unlocked.png"),
    },
    tags: {
      clipTagBeige: classifiedAsset("ui/tags/clip_tag_beige.png"),
      clipTagKraft: classifiedAsset("ui/tags/clip_tag_kraft.png"),
      clipTagOrange: classifiedAsset("ui/tags/clip_tag_orange.png"),
      clipTagSage: classifiedAsset("ui/tags/clip_tag_sage.png"),
      labelBeigeSmall: classifiedAsset("ui/tags/label_beige_small.png"),
      labelKraftSmall: classifiedAsset("ui/tags/label_kraft_small.png"),
      labelOrangeSmall: classifiedAsset("ui/tags/label_orange_small.png"),
      labelSageSmall: classifiedAsset("ui/tags/label_sage_small.png"),
      lockTagBeige: classifiedAsset("ui/tags/lock_tag_beige.png"),
      lockTagKraft: classifiedAsset("ui/tags/lock_tag_kraft.png"),
      lockTagOrange: classifiedAsset("ui/tags/lock_tag_orange.png"),
      lockTagSage: classifiedAsset("ui/tags/lock_tag_sage.png"),
      numberToken1Active: classifiedAsset("ui/tags/number_token_1_active.png"),
      numberToken1Default: classifiedAsset("ui/tags/number_token_1_default.png"),
      numberToken1Disabled: classifiedAsset("ui/tags/number_token_1_disabled.png"),
      numberToken2Active: classifiedAsset("ui/tags/number_token_2_active.png"),
      numberToken2Default: classifiedAsset("ui/tags/number_token_2_default.png"),
      numberToken2Disabled: classifiedAsset("ui/tags/number_token_2_disabled.png"),
      numberToken3Active: classifiedAsset("ui/tags/number_token_3_active.png"),
      numberToken3Default: classifiedAsset("ui/tags/number_token_3_default.png"),
      numberToken3Disabled: classifiedAsset("ui/tags/number_token_3_disabled.png"),
      numberToken4Active: classifiedAsset("ui/tags/number_token_4_active.png"),
      numberToken4Default: classifiedAsset("ui/tags/number_token_4_default.png"),
      numberToken4Disabled: classifiedAsset("ui/tags/number_token_4_disabled.png"),
      numberToken5Active: classifiedAsset("ui/tags/number_token_5_active.png"),
      numberToken5Default: classifiedAsset("ui/tags/number_token_5_default.png"),
      numberToken5Disabled: classifiedAsset("ui/tags/number_token_5_disabled.png"),
      statusBlank: classifiedAsset("ui/tags/status_blank.png"),
      statusBlankSmall: classifiedAsset("ui/tags/status_blank_small.png"),
      statusLineExample: classifiedAsset("ui/tags/status_line_example.png"),
      statusSelected: classifiedAsset("ui/tags/status_selected.png"),
      statusSent: classifiedAsset("ui/tags/status_sent.png"),
      statusSubmitted: classifiedAsset("ui/tags/status_submitted.png"),
      statusSuccess: classifiedAsset("ui/tags/status_success.png"),
      statusWaiting: classifiedAsset("ui/tags/status_waiting.png"),
      statusWritten: classifiedAsset("ui/tags/status_written.png"),
      tagBlueGray: classifiedAsset("ui/tags/tag_blue_gray.png"),
      tagHoleBeige: classifiedAsset("ui/tags/tag_hole_beige.png"),
      tagHoleOrange: classifiedAsset("ui/tags/tag_hole_orange.png"),
      tagHoleSage: classifiedAsset("ui/tags/tag_hole_sage.png"),
      tagOrange: classifiedAsset("ui/tags/tag_orange.png"),
      tagRed: classifiedAsset("ui/tags/tag_red.png"),
      tagSage: classifiedAsset("ui/tags/tag_sage.png"),
      tagSelected: classifiedAsset("ui/tags/tag_selected.png"),
      tapedNoteBlank: classifiedAsset("ui/tags/taped_note_blank.png"),
      ticketTagBeige: classifiedAsset("ui/tags/ticket_tag_beige.png"),
      ticketTagKraft: classifiedAsset("ui/tags/ticket_tag_kraft.png"),
      ticketTagOrange: classifiedAsset("ui/tags/ticket_tag_orange.png"),
      ticketTagSage: classifiedAsset("ui/tags/ticket_tag_sage.png"),
    },
  },
} as const;
